# interfaces/srv/ArmCommand.srv

# Request
float32 x              # X-coordinate (used if command is "move_to_book_spine")
float32 y              # Y-coordinate (used if command is "move_to_book_spine")
float32 z  
float32 qx             # X-coordinate (used if command is "move_to_book_spine")
float32 qy              # Y-coordinate (used if command is "move_to_book_spine")
float32 qz
float32 qw 
---

# Response
bool success           # True if the motion succeeded, false otherwise